theme = "slick"
icons = "awesome"

[[block]]
block = "docker"
interval = 10
format = "{running}/{total}"

[[block]]
block = "disk_space"
path = "/"
format =" {available}"
unit = "GB"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used;G}"
format_swap = "{swap_used;G}"

[[block]]
block = "cpu"
interval = 1
format = "{utilization}"

[[block]]
block = "temperature"
collapsed = false
interval = 5
format = "{max} C"

[[block]]
block = "time"
interval = 5
timezone = "Asia/Kathmandu"
format = "%I:%M%P NE"

[[block]]
block = "time"
interval = 5
timezone = "Europe/Stockholm"
format = "%a %m/%d %H:%M SE"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage} {time}"
