theme = "slick"
icons = "awesome"

[[block]]
block = "notify"

[[block]]
block = "backlight"

[[block]]
block = "time"
interval = 5
timezone = "Asia/Kathmandu"
format = "%I:%M%P NE"

[[block]]
block = "time"
interval = 5
timezone = "Europe/Stockholm"
format = "W%W %a %m/%d %H:%M SE"

[[block]]
block = "disk_space"
path = "/"
format ="{icon} {available}"
unit = "GB"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used;G}"
format_swap = "{swap_used;G}"

[[block]]
block = "cpu"
interval = 1
[block.format]
short = "{utilization}"
full = "{utilization} {frequency}"

[[block]]
block = "temperature"
collapsed = true
interval = 5
format = "{min}•{max}C"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage} {time}"
