theme = "slick"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 20
show_marks = "visible"

[[block]]
block = "music"
on_click = "playerctl play-pause"
hide_when_empty = true

[[block]]
block = "net"
device = "wlp58s0"
format = "{ssid}"
format_alt = "{ssid} {signal_strength} {frequency}"
interval = 5

[[block]]
block = "net"
format = "{ip}"
format_alt = "{ipv6}"
interval = 5

[[block]]
block = "net"
format = "{speed_down;K*b}"
format_alt = "{bitrate} {speed_down;K*b} {speed_up;K*b}"
interval = 5

[[block]]
block = "toggle"
text = "WiFi"
command_state = "ip a | grep wlp58s0 | grep 'state UP'"
command_on = "nmcli radio wifi on"
command_off = "nmcli radio wifi off"

[[block]]
block = "docker"
interval = 10
format = "{running}/{total}"

[[block]]
block = "ibus"
[block.mappings]
"xkb:us::eng" = "EN"
"xkb:us:dvorak:eng" = "DV"
"xkb:se::swe" = "SE"
"xkb:se:dvorak:swe" = "SV"
"m17n:ne:rom" = "NE"

[[block]]
block = "notify"