require("suvim.plugins.packer")
require("suvim.plugins.telescope")
require("suvim.plugins.treesitter")
require("suvim.plugins.nvim-base16")
require("suvim.plugins.undotree")
require("suvim.plugins.vim-fugitive")
require("suvim.plugins.comment")
require("suvim.plugins.luansnip")
require("suvim.plugins.lsp-zero")
require("suvim.plugins.mason")

